#!/usr/bin/env python3
"""tokens_to_tex.py — dump a survey's computed stats tokens as LaTeX \\newcommand macros.

    python3 scripts/survey_scaffold/tokens_to_tex.py <survey_id>

Imports `scripts/<id>_survey/build_survey_page.py` (running its full build as
a side effect — harmless and idempotent, it just rewrites
`public/surveys/<id>.html`) and reads the module-level `tokens` dict it
computes, writing `paper/<id>/tokens.tex` with one `\\newcommand` per token —
so the PDF's numbers come from the *exact same computation* as the site's,
never hand-typed a second time and never at risk of drifting from it.

Requires the survey's `build_survey_page.py` to expose its computed tokens as
a module-level `tokens` dict (`scripts/benchmarks_survey/build_survey_page.py`
and the `scripts/survey_scaffold/templates/` scaffold both already do this —
`tokens = st.compute(...)` — see either for the pattern). A survey whose
builder discards the dict instead of naming it (as `scripts/evaluations_survey/`
still does, pre-dating this convention) needs that one-line change before its
first PDF.
"""
import importlib.util
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from latex_utils import latex_escape  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent.parent

DIGIT_WORDS = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four",
               "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine"}


def die(msg):
    sys.exit(f"tokens_to_tex: {msg}")


def token_to_macro_name(token):
    """LaTeX \\newcommand names must be pure letters — no digits or underscores
    (a TeX control word ends at the first non-letter). 'N_ERA_2122' becomes
    'TokNEraTwoOneTwoTwo': underscores split words, digits spell out, everything
    capitalizes for readability, and a 'Tok' prefix keeps every generated macro
    unambiguously namespaced away from arxiv.sty / LaTeX built-ins."""
    parts = []
    for piece in token.split("_"):
        for seg in re.findall(r"[A-Za-z]+|[0-9]+", piece):
            if seg.isdigit():
                parts.append("".join(DIGIT_WORDS[d] for d in seg))
            else:
                parts.append(seg.capitalize())
    return "Tok" + "".join(parts)


def load_tokens(survey_id):
    survey_dir = ROOT / "scripts" / f"{survey_id}_survey"
    build_script = survey_dir / "build_survey_page.py"
    if not build_script.exists():
        die(f"{build_script} not found — run the 'site' step first.")
    # build_survey_page.py does a bare `import svgcharts`/`import stats_tokens`,
    # resolved relative to its own directory — matches how `cd <dir> && python3
    # build_survey_page.py` is normally invoked, so replicate that sys.path state.
    sys.path.insert(0, str(survey_dir))
    spec = importlib.util.spec_from_file_location(f"{survey_id}_build_survey_page", build_script)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)  # runs the full build as a side effect (idempotent)
    if not hasattr(module, "tokens"):
        die(f"{build_script} has no module-level `tokens` dict — expose the computed "
            f"stats as `tokens = st.compute(...)` (see scripts/benchmarks_survey/ or the "
            f"scaffold template for the pattern) before this script can read them.")
    return module.tokens


def main():
    if len(sys.argv) != 2:
        die("usage: tokens_to_tex.py <survey_id>")
    survey_id = sys.argv[1]
    tokens = load_tokens(survey_id)

    macro_names = {}
    for token in tokens:
        name = token_to_macro_name(token)
        if name in macro_names.values():
            die(f"macro name collision: token {token!r} collides with an earlier "
                f"token at \\{name} — rename one of the source tokens.")
        macro_names[token] = name

    out_dir = ROOT / "paper" / survey_id
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "tokens.tex"
    lines = [
        f"% Auto-generated by scripts/survey_scaffold/tokens_to_tex.py from "
        f"scripts/{survey_id}_survey/build_survey_page.py's computed tokens.",
        "% Do not hand-edit — re-run the script after re-classifying or re-tagging.",
    ]
    for token, name in macro_names.items():
        lines.append(f"\\newcommand{{\\{name}}}{{{latex_escape(tokens[token])}}}")
    out_path.write_text("\n".join(lines) + "\n")
    print(f"wrote {out_path} ({len(macro_names)} macros)")


if __name__ == "__main__":
    main()
